# Generated by Django 4.2.21 on 2025-05-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='joined_date',
            field=models.DateField(default='2024-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.IntegerField(default=2004),
            preserve_default=False,
        ),
    ]
